logging:
  level:
    ROOT: INFO
    com.chtrembl: INFO
    org.springframework: DEBUG
bing:
  search:
    subscription:
      key: ${BING_SEARCH_SUBSCRIPTION_KEY:}
petstore:
  service:
    pet:
     url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
    persistOrder:
      url: ${PETSTOREPERSISTORDERSERVICE_URL:http://localhost:7071/api/orders/123}
  logging:
    additional-headers-to-log: ${PETSTORE_ADDITIONAL_HEADERS_TO_LOG:}
    additional-headers-to-send: ${PETSTORE_ADDITIONAL_HEADERS_TO_SEND:}
  signalR:
    negotiation-url: ${SIGNALR_NEGOTIATION_URL:}
    service-url: ${SIGNALR_SERVICE_URL:}
    key: ${SIGNALR_SERVICE_KEY:}
    update:
      fixedRate: ${SIGNALR_UPDATE_FIXEDRATE:60000}
server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}
azure:
  application-insights:
    instrumentation-key: ${PETSTOREAPP_AI_INSTRUMENTATION_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: ${PETSTOREAPP_B2C_TENANT}
          oidc-enabled: true
          credential:
            client-id: ${PETSTOREAPP_B2C_CLIENT_ID}
            client-secret: ${PETSTOREAPP_B2C_CLIENT_SECRET}
          reply-url: ${PETSTOREAPP_B2C_REPLY_URL}
          login-flow: sign-up-or-sign-in
          logout-success-url: ${PETSTOREAPP_B2C_LOGOUT_URL}
          user-flows:
            sign-up-or-sign-in: B2C_1_petstore_sign
            profile-edit: B2C_1_profile_edit
            password-reset: B2C_1_pwd_reset
